// Client script: loads wishlist, renders gallery and handles uploads.
(async function () {
  const wishlistContainer = document.getElementById('wishlist-container');
  const gallery = document.getElementById('gallery');
  const uploadBtn = document.getElementById('upload-btn');
  const photoInput = document.getElementById('photo-input');
  const uploadStatus = document.getElementById('upload-status');

  // Load wishlist
  async function loadWishlist() {
    try {
      const res = await fetch('data/wishlist.json');
      const data = await res.json();
      renderWishlist(data);
    } catch (e) {
      wishlistContainer.innerText = 'Could not load wishes.';
      console.error(e);
    }
  }

  function renderWishlist(list) {
    if (!Array.isArray(list) || list.length === 0) {
      wishlistContainer.innerHTML = '<p>No wishes yet — check back soon.</p>';
      return;
    }
    wishlistContainer.innerHTML = '';
    list.forEach(w => {
      const el = document.createElement('div'); el.className = 'wish';
      const title = document.createElement('h3'); title.innerText = w.title || 'Untitled';
      const desc = document.createElement('p'); desc.innerText = w.description || '';
      el.appendChild(title); el.appendChild(desc);
      if (w.link) {
        const a = document.createElement('a'); a.href = w.link; a.target = '_blank'; a.innerText = 'More info';
        el.appendChild(a);
      }
      wishlistContainer.appendChild(el);
    });
  }

  // Cloudinary gallery & upload (requires config.js with CLOUDINARY_CLOUD_NAME and UPLOAD_PRESET)
  function cloudinaryUrl(path) {
    return `https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/${path}`;
  }

  async function loadGallery() {
    // First try a local static manifest generated by the admin helper: data/gallery.json
    try {
      const local = await fetch('data/gallery.json');
      if (local.ok) {
        const list = await local.json();
        if (Array.isArray(list) && list.length > 0) { renderGallery(list); return }
      }
    } catch (e) { /* ignore and fallback */ }

    // Fallback: try Cloudinary public list endpoint if configured
    if (!window.CLOUDINARY_CLOUD_NAME) { gallery.innerHTML = '<p>Gallery not configured. See README.</p>'; return }
    try {
      const url = `https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/image/list/wedding-photos.json`;
      const res = await fetch(url);
      if (!res.ok) throw new Error('Failed to fetch gallery');
      const list = await res.json();
      renderGallery(list.resources || list);
    } catch (e) {
      gallery.innerHTML = '<p>Could not load gallery.</p>';
      console.error(e);
    }
  }

  function renderGallery(items) {
    if (!items || items.length === 0) {
      // If there are already items in the gallery (e.g. just uploaded), keep them.
      if (!gallery.querySelector('.gallery-item')) {
        gallery.innerHTML = '<p>No photos yet.</p>';
      }
      return
    }

    items.forEach(it => {
      const wrap = document.createElement('div'); wrap.className = 'gallery-item';
      const img = document.createElement('img');
      // support different resource shapes
      const publicId = it.public_id || it.url || it.path || it.name;
      let src = '';
      if (it.url) { src = it.url }
      else if (it.secure_url) { src = it.secure_url }
      else if (it.public_id) { src = cloudinaryUrl(`image/upload/${it.public_id}.jpg`) }
      // duplicates are allowed
      img.src = src;
      img.alt = it.public_id || 'wedding photo';
      wrap.appendChild(img);

      // download button/link
      const actions = document.createElement('div'); actions.className = 'gallery-actions';
      const dl = document.createElement('a'); dl.href = src; dl.innerText = 'Download'; dl.className = 'btn btn-download';
      dl.setAttribute('target', '_blank');
      dl.setAttribute('rel', 'noopener');
      actions.appendChild(dl);
      // (Removed Cloudinary console link per request)
  wrap.appendChild(actions);

      gallery.appendChild(wrap);
      // duplicates allowed or handled at upload time
    })
  }

  // Append items to the existing gallery without wiping current DOM (used after upload)
  function appendGalleryItems(items) {
    if (!items || items.length === 0) return;
    items.forEach(it => {
      const wrap = document.createElement('div'); wrap.className = 'gallery-item';
      const img = document.createElement('img');
      const publicId = it.public_id || it.url || it.path || it.name;
      let src = '';
      if (it.url) { src = it.url }
      else if (it.secure_url) { src = it.secure_url }
      else if (it.public_id) { src = cloudinaryUrl(`image/upload/${it.public_id}.jpg`) }
      img.src = src; img.alt = it.public_id || 'wedding photo';
      wrap.appendChild(img);
      const actions = document.createElement('div'); actions.className = 'gallery-actions';
      const dl = document.createElement('a'); dl.href = src; dl.innerText = 'Download'; dl.className = 'btn btn-download';
      dl.setAttribute('target', '_blank'); dl.setAttribute('rel', 'noopener');
      actions.appendChild(dl);
      // (Removed Cloudinary console link per request)
  wrap.appendChild(actions);
      gallery.appendChild(wrap);
    })
  }

  // Download all images currently shown in the gallery
  async function downloadAll() {
    const imgs = Array.from(gallery.querySelectorAll('img'));
    if (imgs.length === 0) return alert('No images to download.');
    // Download sequentially to avoid triggering too many parallel requests
    for (const img of imgs) {
      try {
        const url = img.src;
        // fetch the binary and create a blob download
        const res = await fetch(url);
        if (!res.ok) throw new Error(`Failed to download ${url}`);
        const blob = await res.blob();
        const a = document.createElement('a');
        const objectUrl = URL.createObjectURL(blob);
        a.href = objectUrl;
        // Derive filename from public_id or url
        const filename = (img.alt && !img.alt.includes('wedding photo')) ? img.alt + (blob.type ? ('.' + blob.type.split('/')[1]) : '') : url.split('/').pop().split('?')[0];
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(objectUrl);
        // small pause to be nicer to bandwidth
        await new Promise(r => setTimeout(r, 300));
      } catch (e) { console.warn('downloadAll item failed', e); }
    }
  }
  async function uploadFiles(files) {
    if (!window.CLOUDINARY_CLOUD_NAME || !window.UPLOAD_PRESET) {
      uploadStatus.innerText = 'Upload not configured. See README to set up Cloudinary.'; return;
    }
    uploadStatus.innerText = 'Uploading...';
    const uploads = Array.from(files).map(async file => {
      const fd = new FormData();
      fd.append('file', file);
      fd.append('upload_preset', UPLOAD_PRESET);
      fd.append('tags', 'wedding-photos');
      const resp = await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`, { method: 'POST', body: fd });
      let body = null;
      try { body = await resp.json(); } catch (err) { /* ignore parse errors */ }
      if (!resp.ok) {
        const msg = (body && (body.error && body.error.message)) ? body.error.message : `HTTP ${resp.status}`;
        throw new Error(`${file.name}: ${msg}`);
      }
      return body;
    });

    try {
      const results = await Promise.all(uploads);
      uploadStatus.innerText = `Uploaded ${results.length} file(s). Showing uploaded images...`;
      // Immediately show uploaded images in the gallery without waiting for the server-side manifest
      const uploadedItems = results.map(r => ({ public_id: r.public_id, url: r.secure_url || r.url, format: r.format }));
      try {
        // append uploaded items into current gallery display
        appendGalleryItems(uploadedItems);
      } catch (e) { console.warn('Could not render uploaded items immediately', e) }
      // Do not forcibly reload the entire gallery (can cause flicker if server-side listing fails).
      setTimeout(() => { uploadStatus.innerText = ''; }, 1000);
    } catch (e) {
      uploadStatus.innerText = `Upload failed: ${e.message || e}`; console.error('Upload error', e);
    }
  }

  uploadBtn.addEventListener('click', () => {
    (async () => {
      const files = photoInput.files;
      if (!files || files.length === 0) return alert('Choose at least one photo');
      uploadStatus.innerText = 'Checking files...';
      const { ok, bad, dup, stored } = await prepareAndFilterFiles(files);
      if (bad.length) { uploadStatus.innerText = bad.join('; '); return; }
      if (dup.length) { uploadStatus.innerText = dup.join('; '); return; }
      if (ok.length === 0) { uploadStatus.innerText = 'No new files to upload.'; return; }
      try {
        await uploadFiles(ok, stored);
      } catch (e) { console.error(e); }
    })();
  })

  // Wire download all button
  const downloadAllBtn = document.getElementById('download-all-btn');
  if (downloadAllBtn) downloadAllBtn.addEventListener('click', downloadAll);
  // admin UI removed
  // Validate files and prevent duplicates by hashing (client-side)
  const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB
  function validateBasic(file) {
    if (!file.type || !file.type.startsWith('image/')) return `${file.name}: not an image`;
    if (file.size > MAX_FILE_SIZE) {
      const mb = Math.round(file.size / (1024 * 1024));
      return `${file.name}: ${mb}MB exceeds ${MAX_FILE_SIZE / (1024 * 1024)}MB`;
    }
    return null;
  }

  // Compute SHA-1 hash of a File using SubtleCrypto; returns hex string
  async function hashFile(file) {
    const buf = await file.arrayBuffer();
    const hashBuffer = await crypto.subtle.digest('SHA-1', buf);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    return hashHex;
  }

  function loadStoredHashes() {
    try {
      const raw = localStorage.getItem('uploaded_image_hashes');
      if (!raw) return new Set();
      const arr = JSON.parse(raw);
      return new Set(arr);
    } catch (e) { return new Set(); }
  }

  function saveStoredHashes(set) {
    try { localStorage.setItem('uploaded_image_hashes', JSON.stringify(Array.from(set))); } catch (e) { console.warn('Could not save hashes', e); }
  }

  // Prepare files: basic validation + compute hashes and filter duplicates (in-storage and within selection)
  async function prepareAndFilterFiles(fileList) {
    const stored = loadStoredHashes();
    const ok = [];
    const bad = [];
    const dup = [];
    const seen = new Set(); // hashes seen in this selection
    for (const f of Array.from(fileList)) {
      const err = validateBasic(f);
      if (err) { bad.push(err); continue; }
      let h;
      try { h = await hashFile(f); } catch (e) { bad.push(`${f.name}: could not hash file`); continue; }
      if (stored.has(h)) { dup.push(`${f.name}: duplicate (already uploaded)`); continue; }
      if (seen.has(h)) { dup.push(`${f.name}: duplicate in selection`); continue; }
      seen.add(h);
      // attach hash for later use
      f._hash = h;
      ok.push(f);
    }
    return { ok, bad, dup, stored };
  }

  await loadWishlist();
  await loadGallery();
  // debug log removed
})();
